# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trix_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hidden',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Hide assignment from students'),
        ),
    ]
