# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trix_core', '0004_user_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='If you want your students to be able to view a suggested solution, write the solution here.', verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='howsolved',
            name='howsolved',
            field=models.CharField(choices=[('bymyself', 'Solved by myself'), ('withhelp', 'Solved with help')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permalink',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='permalink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'No category'), ('c', 'Course'), ('p', 'Period')], default='', max_length=1),
        ),
    ]
