# Generated by Django 3.2.16 on 2022-11-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trix_core', '0006_auto_20221121_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='hidden',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Hide assignment from students'),
        ),
        migrations.AlterField(
            model_name='course',
            name='active_period',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'p'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_period_set', to='trix_core.tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_tag',
            field=models.ForeignKey(limit_choices_to={'category': 'c'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='trix_core.tag'),
        ),
    ]
