# Generated by Django 4.2.6 on 2023-12-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trix_core', '0007_auto_20221130_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, help_text='Is this course visible to students?', verbose_name='Visible?'),
        ),
    ]
